[DEX] Preview/Unauthenticated Mode
aphtoken/aph-desktop-web-dex pull request #10
Opened 2019-03-10 06:22 UTC by crishellco

## Ticket
* n/a

## Changes
* Update auth gates
* Disable wallet-specific requests during preview
* Login landing preview link
* Other UI tweaks
* Remove legacy code from desktop app

## Screenshots
![image](https://user-images.githubusercontent.com/1878509/54081427-11b9f900-42c2-11e9-83be-4c7d62a0d8c0.png)
![image](https://user-images.githubusercontent.com/1878509/54081429-1a123400-42c2-11e9-8159-f59133ffdd07.png)

## Code Coverage
n/a

2019-03-10 06:38 UTC, jsolman commented on src/router/index.js
> +  mode: 'history',
Need to remove this. Doesn’t work week with the way we are hosting the static assets.

2019-03-10 19:34 UTC, jsolman commented on src/router/index.js
> +  mode: 'history',
I made the change and adjusted navigating to the login screen.

2019-03-10 19:36 UTC, jsolman submitted a review, later dismissed

2019-03-10 19:40 UTC, apheliontoken submitted a review, later dismissed
After logging out subsequently clicking `Explore the DEX` displays the `Login To Trade` button wrong.

![Screenshot from 2019-03-10 12-41-16](https://user-images.githubusercontent.com/32698425/54090492-fbe41c80-4331-11e9-97d0-3298aa439728.png)

Refreshing the page fixes the issue.

2019-03-10 22:01 UTC, eddieharrison commented
`handleMountedIfPreviewing` doesn't dispatch `fetchHoldings` and therefore `getValuations` isn't called.. this is what brings in the $ volume values and is missing from the explore mode at the moment. Please see attached screenshot.

![Screen Shot 2019-03-10 at 21 57 40](https://user-images.githubusercontent.com/1763818/54092100-062d0780-4380-11e9-8526-1c4755fb2ce3.png)

2019-03-11 20:30 UTC, jsolman requested changes

2019-03-11 20:30 UTC, jsolman commented on src/components/dex/MarketMegaSelector.vue
> +          const unitValue = baseAsset ? baseAsset.unitValue : market.unitValue || 0;
This unit value needs to be the market's base asset unit value, it seems you have set `market.unitValue` to the quote asset unit value.

2019-03-11 20:30 UTC, jsolman commented on src/components/dex/MarketMegaSelector.vue
> +          const unitValue = baseAsset ? baseAsset.unitValue : market.unitValue || 0;
It would also be better to name it `market.baseUnitValue`

2019-03-11 20:30 UTC, jsolman commented on src/store/mutations.js
> +    const valuation = valuations[market.quoteCurrency];
`baseCurrency` is the one needed.

2019-03-12 06:49 UTC, jsolman commented on src/components/Dex.vue
> +        symbols: _.map(markets, 'quoteCurrency'),
This needs to load `baseCurrency` valuations also, or perhaps only `baseCurrency` valuations, since those are all that are being used.

2019-03-12 06:49 UTC, jsolman commented on src/store/mutations.js
> +  state.markets = state.markets.map((market) => {
This could get the markets with uniq base currencies first, so it doesn't iterate the same `market.baseCurrency` repeatedly many times.

2019-03-12 23:27 UTC, jsolman commented on src/store/mutations.js
> +  state.markets = state.markets.map((market) => {
Actually, to do that it would have to work differently; you can disregard this comment.

2019-03-13 16:41 UTC, jsolman commented on src/components/Dex.vue
> +        symbols: _.map(markets, 'quoteCurrency'),
I made it include the `baseCurrency` also.

2019-03-13 16:41 UTC, jsolman approved these changes

2019-03-13 16:44 UTC, merged